### ISSUE TITLE
looked at the source code

### ISSUE THREAD

**Issue by lnnnn123** [ar4/deepwave#70]
Sorry for disturbing. When I looked at the source code, I found that I could not find the code shown in the image. And I have modified the form of the source wave equation. Do you think this idea can be realized？
![1714641869601](https://github.com/ar4/deepwave/assets/168723521/87cee96d-0669-4bd8-b6ce-a145366adc5a)

**Comment by lnnnn123** [comment]
I looked in the pytorch package and found this, but I couldn't find the exact location. I want to change the expression of the wave equation, add some pseudo-spectral operation, I wonder whether it is feasible?

**Comment by ar4** [comment]
Ah, I see. You have not yet modified Deepwave; you wish to modify it to
change the way that the wave equation is implemented. I do not have
experience with pseudo-spectral methods, so I am not sure what is needed,
but if your question is where the wave equation is implemented in Deepwave,
you can find the C implementation of the scalar wave equation in the file
https://github.com/ar4/deepwave/blob/master/src/deepwave/scalar.c . The
forward wave equation, in particular, is here:
https://github.com/ar4/deepwave/blob/53862031102ee759388700e77b57dd13c1729ba9/src/deepwave/scalar.c#L83
. It is currently a standard finite difference implementation (see the last
line in that function), but looks a little bit complicated because of the
PML to add absorbing boundaries.

**Comment by lnnnn123** [comment]
Ok, I have roughly understood your meaning, thank you for your reply

**Comment by ar4** [comment]
Good, but just to be sure, I will try to explain it again.

Most people just want to install Deepwave and use it, without modifying
Deepwave's code. They can use pip to install it. So that the C/CUDA code
does not need to be compiled on their computer (which sometimes causes
problems), pip downloads already compiled libraries of the C/CUDA code. It
therefore does not need the C/CUDA code itself.

If you wish to modify the C/CUDA code, you need the C/CUDA code, not the
already compiled libraries of it. Therefore instead of running `pip install
deepwave`, you will need to download the code (which includes the C/CUDA
code) from GitHub. You can then modify it and compile it yourself.

**Comment by ar4** [comment]
I hope this Issue is resolved, so I am going to close it. Please feel free to reopen it if you have further questions about this.
